sequences:
- protein:
    id: [A]
    sequence: SMENFQKVEKIGEGTYGVVYKARNKLTGEVVALKKIRLDTETEGVPSTAIREISLLKELNHPNIVKLLDVIHTENKLYLVFEFLHQDLKKFMDASALTGIPLPLIKSYLFQLLQGLAFCHSHRVLHRDLKPQNLLINTEGAIKLADFGLARAFGVPVRTYAHEVVTLWYRAPEILLGCKYYSTAVDIWSLGCIFAEMVTRRALFPGDSEIDQLFRIFRTLGTPDEVVWPGVTSMPDYKPSFPKWARQDFSKVVPPLDEDGRSLLSQMLHYDPNKRISAKAALAHPFFQDVTKPVPHL
- ligand:
    id: [B]
    smiles: c1ccc(Nc2nc(OCC3CCCCC3)c3[nH]cnc3n2)cc1
constraints:
- pocket:
    binder: B
    contacts: [[A, 82], [A, 84], [A, 85], [A, 132]]
    force: true
properties:
- affinity: {binder: B}
